server:
  port: 8888
  servlet:
    session:
      tracking-modes: cookie
spring:
  application:
    name: rest
  profiles:
    active:
  data:
    rest:
      base-path: api/v1
  datasource:
    url: jdbc:mysql://localhost:3306/java6_asm
    username: root
    password:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        show_sql: true
    show-sql: false
  jackson:
    deserialization:
      fail-on-unknown-properties: false
logging:
  level:
    sql:
    web: trace

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:asm-java6;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: bsData
  jpa:
    hibernate:
      ddl-auto: create
