spring:
  #    Config h2 to work with MySQL
  datasource:
    url: jdbc:h2:mem:asm-java6;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        show_sql: false
    show-sql: true
  data:
    rest:
      base-path: api/v1
  profiles:
    active: prod
  security:
    user:
      name: user
      password: 123
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  autoconfigure:
    exclude:
      org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
logging:
  level:
    web: trace
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/java6_asm
    username: root
    password:
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    web: info
