server:
  port: 8082
spring:
  application:
    name: admin
#  mvc:
#    view:
#      suffix: .html
#      prefix: classpath:/templates/

eureka:
  client:
    enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
logging:
  level:
    web: info
