server:
  port: 8081

api:
  base-path: http://rest/api/v1

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  application:
    name: cart

eureka:
  client:
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
